[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488E2430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/76a1837eb522c6572dc6d669ef411697
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488E2700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/76a1837eb522c6572dc6d669ef411697
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488E20D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/76a1837eb522c6572dc6d669ef411697