[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488D23A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bdfcb2fb1627eaf72bc34f82cc8c19c9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488D2670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bdfcb2fb1627eaf72bc34f82cc8c19c9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488D20A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bdfcb2fb1627eaf72bc34f82cc8c19c9