[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488C61C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/cfd1b3c6a6558583b4d879463012f4a1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488D2880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/cfd1b3c6a6558583b4d879463012f4a1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488D2C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/cfd1b3c6a6558583b4d879463012f4a1