[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C48879C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/84f7e62dbc095a39e9f6324d3338dea0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488A6670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/84f7e62dbc095a39e9f6324d3338dea0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488A68E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/84f7e62dbc095a39e9f6324d3338dea0